import { precacheAndRoute } from 'workbox-precaching'

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)

// Helper for IndexedDB access in Service Worker
const getFromIDB = (key) => {
    return new Promise((resolve) => {
        const request = indexedDB.open('japa-settings', 1);
        request.onupgradeneeded = (e) => e.target.result.createObjectStore('settings');
        request.onsuccess = (e) => {
            const db = e.target.result;
            const transaction = db.transaction('settings', 'readonly');
            const store = transaction.objectStore('settings');
            const getRequest = store.get(key);
            getRequest.onsuccess = () => resolve(getRequest.result);
            getRequest.onerror = () => resolve(null);
        };
        request.onerror = () => resolve(null);
    });
};

// Function to show the notification
const showReminder = (isTest = false) => {
    self.registration.showNotification(isTest ? 'Japa Test Notification 🌸' : 'Naam Japa Reminder', {
        body: isTest ? 'Your notification system is working perfectly! Radhe Radhe! 🙏' : 'Radhe Radhe! It is time for your sacred Naam Japa. 🙏',
        icon: '/icon.svg',
        badge: '/icon.svg',
        vibrate: [200, 100, 200],
        tag: 'japa-reminder',
        renotify: true,
        data: {
            url: '/'
        }
    });
};

// Background logic for notifications
self.addEventListener('message', async (event) => {
    if (event.data && event.data.type === 'TEST_NOTIFICATION') {
        showReminder(true);
    }
});

// Powerful Background Timer (Runs when SW is active)
let lastCheckedMinutes = -1;

setInterval(async () => {
    const now = new Date();
    const currentMinutes = now.getMinutes();

    // Only check once per minute
    if (currentMinutes === lastCheckedMinutes) return;
    lastCheckedMinutes = currentMinutes;

    const settings = await getFromIDB('notificationSettings');
    if (!settings || !settings.enabled) return;

    const [targetH, targetM] = settings.time.split(':').map(Number);

    if (now.getHours() === targetH && now.getMinutes() === targetM) {
        showReminder();
    }
}, 30000); // Check every 30 seconds to be safe

self.addEventListener('notificationclick', (event) => {
    event.notification.close();
    event.waitUntil(
        clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
            if (clientList.length > 0) {
                let client = clientList[0];
                for (let i = 0; i < clientList.length; i++) {
                    if (clientList[i].focused) {
                        client = clientList[i];
                    }
                }
                return client.focus();
            }
            return clients.openWindow('/');
        })
    );
});
